apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification
  name: notification
spec:
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: notification
  type: ClusterIP
